# Generated by Django 4.2.8 on 2026-02-06 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.IntegerField(db_index=True, help_text='Уникальный идентификатор из конкурсных списков', unique=True, verbose_name='ID абитуриента')),
                ('physics_ict_score', models.IntegerField(help_text='Балл по физике или ИКТ (45-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Балл Физика/ИКТ')),
                ('russian_score', models.IntegerField(help_text='Балл по русскому языку (45-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Балл Русский язык')),
                ('math_score', models.IntegerField(help_text='Балл по математике (45-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Балл Математика')),
                ('achievements_score', models.IntegerField(help_text='Балл за индивидуальные достижения (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Балл ИД')),
                ('total_score', models.IntegerField(db_index=True, help_text='Общая сумма баллов', verbose_name='Сумма баллов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Абитуриент',
                'verbose_name_plural': 'Абитуриенты',
                'db_table': 'applicants',
                'ordering': ['-total_score', 'applicant_id'],
                'indexes': [models.Index(fields=['applicant_id'], name='idx_applicant_id'), models.Index(fields=['-total_score'], name='idx_total_score')],
            },
        ),
    ]
