# Generated by Django 4.2.8 on 2026-02-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='applicant',
            name='idx_applicant_id',
        ),
        migrations.RemoveIndex(
            model_name='applicant',
            name='idx_total_score',
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['-total_score', 'applicant_id'], name='idx_score_id'),
        ),
    ]
