# Generated by Django 4.2.8 on 2026-02-06 05:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Краткий код программы (например, PM, IVT)', max_length=10, unique=True, verbose_name='Код программы')),
                ('name', models.CharField(help_text='Полное название образовательной программы', max_length=200, verbose_name='Название программы')),
                ('seats', models.IntegerField(help_text='Количество бюджетных мест на программе', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество мест')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о программе', null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
                'db_table': 'programs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Когда были загружены данные', verbose_name='Дата и время загрузки')),
                ('records_count', models.IntegerField(help_text='Сколько записей было загружено', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество записей')),
                ('competition_date', models.DateField(help_text='Дата из конкурсных списков (например, 01.08.2024)', verbose_name='Дата конкурса')),
                ('programs_stats', models.JSONField(blank=True, default=dict, help_text='Количество записей по каждой программе', verbose_name='Статистика по программам')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о загрузке', null=True, verbose_name='Примечания')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('partial', 'Частично'), ('failed', 'Ошибка')], default='success', help_text='Статус завершения загрузки', max_length=20, verbose_name='Статус')),
                ('uploaded_by', models.CharField(blank=True, help_text='Кто загрузил данные', max_length=100, null=True, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'История загрузки',
                'verbose_name_plural': 'История загрузок',
                'db_table': 'upload_history',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['-upload_date'], name='idx_upload_date'), models.Index(fields=['competition_date'], name='idx_comp_date')],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(help_text='Приоритет программы для абитуриента (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Приоритет')),
                ('consent', models.BooleanField(db_index=True, default=False, help_text='Предоставил ли абитуриент согласие на зачисление', verbose_name='Согласие на зачисление')),
                ('application_date', models.DateField(db_index=True, help_text='Дата подачи заявления (из конкурсных списков)', verbose_name='Дата заявления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('applicant', models.ForeignKey(help_text='Абитуриент, подавший заявление', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applicants.applicant', verbose_name='Абитуриент')),
                ('program', models.ForeignKey(help_text='Образовательная программа', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Заявление',
                'verbose_name_plural': 'Заявления',
                'db_table': 'applications',
                'ordering': ['application_date', 'program', '-applicant__total_score'],
                'indexes': [models.Index(fields=['program', 'application_date'], name='idx_prog_date'), models.Index(fields=['application_date', 'consent'], name='idx_date_consent'), models.Index(fields=['applicant', 'application_date'], name='idx_appl_date'), models.Index(fields=['program', 'application_date', 'priority'], name='idx_prog_date_prior')],
                'unique_together': {('applicant', 'program', 'application_date')},
            },
        ),
    ]
