# Generated by Django 4.2.8 on 2026-02-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='color',
            field=models.CharField(default='rgb(128, 128, 128)', help_text='Цвет в формате rgb(R, G, B)', max_length=50, verbose_name='Цвет для графиков'),
        ),
    ]
