# Generated by Django 4.2.8 on 2026-02-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_program_color'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='application',
            name='idx_prog_date_prior',
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_date', 'applicant', 'program'], name='idx_date_appl_prog'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'program', 'application_date'], name='idx_unique_check'),
        ),
    ]
